const initialState = {
  user: {
    facility: {},
    areas: [],
    allZones: [],
    zones: [],
    selectedAreaId: null,
    isLoading: false,
    error: null,
    whereUserWorks: [],
  },
  events: {
    isLoading: false,
    error: false,
    types: [],
  },
  schedule: {
    isLoading: false,
    error: null,
    scheduleItems: [],
    scheduleItem: {
      district_id: '',
      event_type_id: '',
      participant_count: 0,
      responsible_organization_id: '',
      responsible_person_type_id: '',
      sport_type_id: '',
      title: '',
    },
    monthEvents: [],
    monthEventsAll: [],
    orgFilter: {
      id: 0,
      organizationName: 'Все организации',
    },
    areaFilter: {
      id: 0,
      name: 'Все помещения',
    },
    zoneFilter: {
      id: 0,
      name: 'Все зоны',
    },
    zones: [],
  },
  coach: {
    all: [],
    coaches: [],
    allSports: [],
    allDisciplines: [],
    currentCoach: {
      id: '',
      fio: '',
      avatar: '',
      ranks: [],
    },
    isModalOpen: false,
    sports: [],
    searchValue: '',
    sportFilter: { id: 1, item: 'Все виды спорта' },
    allowedSports: [{ id: 1, item: 'Все виды спорта' }],
    loading: false,
    isError: false,
    pageSize: 10,
    currentPage: 0,
    pages: 1,
    total: 0,
  },
  registry: {
    facilitySports: [],
    facilityDisciplines: [],
    ranksAll: [
      {
        id: '45bf4a98-2de5-4ead-bd42-dbab68c7e10a',
        name: 'Без звания',
        acronym: 'БЗ',
        sortOrder: 0,
      },
      {
        id: '133c876b-1dd5-4ad3-8884-15d5310a580a',
        name: 'Третий юношеский спортивный разряд',
        acronym: '3 юн. разряд',
        sortOrder: 1,
      },
    ],
    fullSports: [
      {
        id: 'fdd355f1-9529-451f-8eb7-c7d80a03c095',
        code: '0030004611Я',
        title: 'Хоккей',
        disciplinesCount: 1,
        disciplines: [
          {
            id: '8367acc5-369a-49cb-9e1e-4f040a049fa5',
            code: '0030014611Я',
            title: 'хоккей',
          },
        ],
      },
      {
        id: '97da130f-9fbd-4115-9081-0fb5f9fd0da1',
        code: '0010002611Я',
        title: 'Футбол',
        disciplinesCount: 1,
        disciplines: [
          {
            id: '2612447b-aaaa-46cf-a91c-ec33ccc94d97',
            code: '0010012611Я',
            title: 'футбол',
          },
        ],
      },
    ],
  },
  foundation: {
    all: [],
    contracts: [],
    orgTypes: [],
    zones: [],
    contractTypes: [],
    currentContract: {
      legalData: '',
      organizationName: '',
      zoneTitle: '',
      zones: [],
      files: [
        {
          key: 0,
          name: '',
        },
      ],
      id: '',
    },
    contractOrganization: {},
    isModalOpen: false,
    searchValue: '',
    sportFilter: { id: 1, item: 'Все виды спорта' },
    allowedSports: [{ id: 1, item: 'Все виды спорта' }],
    typeFilter: { id: 1, item: 'Все типы организаций' },
    allowedTypes: [{ id: 1, item: 'Все типы организаций' }],
    loading: false,
    isError: false,
    pageSize: 10,
    currentPage: 0,
    pages: 1,
    total: 0,
  },
}

export const mockUser = {
  email: 'bicycle@me.com',
  expiresIn: 359,
  facilities: ['b44b0857-a06f-492d-9a39-38e340012445'],
  federations: [],
  firstName: 'Пётр',
  jti: 'd190a5d4-4c5f-4b74-a6ce-d2918cfdf3b4',
  organizations: ['ae9d45de-a14b-4c4a-b296-541d55377885'],
  patronymicName: 'Леонидович',
  phone: '+7007',
  surName: 'Лисапедов',
  time: '2019-11-19T13:54:33.962Z',
  tokenType: 'bearer',
  workPlace: { type: 'facilities', id: 'b44b0857-a06f-492d-9a39-38e340012445' },
}

export default initialState
