const PREFIX = 'FOUNDATION'

export const SET_CONTRACTS = `${PREFIX}/SET_CONTRACTS`
export const SET_ALLOWED_SPORTS = `${PREFIX}/SET_ALLOWED_SPORTS`
export const SET_ALLOWED_TYPES = `${PREFIX}/SET_ALLOWED_TYPES`
export const SET_LOADING = `${PREFIX}/SET_LOADING`
export const UPDATE_LIST = `${PREFIX}/UPDATE_LIST`
export const SET_SPORT_FILTER = `${PREFIX}/SET_SPORT_FILTER`
export const SET_TYPE_FILTER = `${PREFIX}/SET_TYPE_FILTER`
export const SET_NAME_SEARCH = `${PREFIX}/SET_NAME_SEARCH`
export const SET_MODAL = `${PREFIX}/SET_MODAL`
export const SET_CURRENT_CONTRACT = `${PREFIX}/SET_CURRENT_CONTRACT`
export const SET_ORG_TYPES = `${PREFIX}/SET_ORG_TYPES`
export const SET_CONTRACT_TYPES = `${PREFIX}/SET_CONTRACT_TYPES`
export const SET_ORGANIZATIONS = `${PREFIX}/SET_ORGANIZATIONS`
export const SET_CONTRACT_ORGANIZATION = `${PREFIX}/SET_CONTRACT_ORGANIZATION`
export const SET_ORGANIZATION_CONTRACTS = `${PREFIX}/SET_ORGANIZATION_CONTRACTS`
