const PREFIX = 'REGISTRY'

export const SET_REGISTRY_FULL_PERSONS = `${PREFIX}/SET_REGISTRY_FULL_PERSONS`
export const SET_REGISTRY_LOADING = `${PREFIX}/SET_REGISTRY_LOADING`
export const SET_REGISTRY_ERROR = `${PREFIX}/SET_REGISTRY_ERROR`
export const SET_RANKS_ALL = `${PREFIX}/SET_RANKS_ALL`
export const SET_FEDERATIONS_ALL = `${PREFIX}/SET_FEDERATIONS_ALL`
export const SET_PERSONS_MODE = `${PREFIX}/SET_PERSONS_MODE`
export const SET_SINGLE_PERSON = `${PREFIX}/SET_SINGLE_PERSON`
export const SET_CURRENT_PAGE = `${PREFIX}/SET_CURRENT_PAGE`
export const SET_FULL_SPORTS = `${PREFIX}/SET_FULL_SPORTS`
export const SET_FULL_DISCIPLINES = `${PREFIX}/SET_FULL_DISCIPLINES`
export const SET_FACILITY_SPORTS = `${PREFIX}/SET_FACILITY_SPORTS`
export const SET_FACILITY_DISCIPLINES = `${PREFIX}/SET_FACILITY_DISCIPLINES`

export const SET_SPORT_FILTER = `${PREFIX}/SET_SPORT_FILTER`
export const SET_RANK_FILTER = `${PREFIX}/SET_RANK_FILTER`
export const SET_GROUP_FILTER = `${PREFIX}/SET_GROUP_FILTER`
export const SET_SEARCH_VALUE = `${PREFIX}/SET_SEARCH_VALUE`
