const PREFIX = 'SCHEDULE'

export const ADD_ITEM = `${PREFIX}/ADD_ITEM`
export const SET_IS_LOADING = `${PREFIX}/SET_IS_LOADING`
export const SET_ERROR = `${PREFIX}/SET_ERROR`

export const SET_ORG_FILTER = `${PREFIX}/SET_ORG_FILTER`
export const SET_AREA_FILTER = `${PREFIX}/SET_AREA_FILTER`
export const SET_ZONE_FILTER = `${PREFIX}/SET_ZONE_FILTER`

export const SET_EVENTS = `${PREFIX}/SET_EVENTS`
export const SET_SCHEDULES = `${PREFIX}/SET_SCHEDULES`
export const SET_CURRENT_DATE = `${PREFIX}/SET_CURRENT_DATE`
export const SET_SCHEDULE_MODAL = `${PREFIX}/SET_SCHEDULE_MODAL`
export const SET_SELECTED_SCHEDULE_ID = `${PREFIX}/SET_SELECTED_SCHEDULE_ID`

export const SET_SCHEDULE_ITEM_FOR_EDIT = `${PREFIX}/SET_SCHEDULE_ITEM_FOR_EDIT`
export const SET_SCHEDULE_ITEM_REPEAT_TYPES = `${PREFIX}/SET_SCHEDULE_ITEM_REPEAT_TYPES`
