const PREFIX = 'FACILITY'

export const SET_FACILITY = `${PREFIX}/SET_FACILITY`
export const SET_AREAS = `${PREFIX}/SET_AREAS`
export const SET_IS_LOADING = `${PREFIX}/SET_IS_LOADING`
export const SET_ERROR = `${PREFIX}/SET_ERROR`
export const SET_ZONES = `${PREFIX}/SET_ZONES`
export const SELECT_AREA_ID = `${PREFIX}/SELECT_AREA_ID`
export const SET_ALL_ZONES = `${PREFIX}/SET_ALL_ZONES`
export const SET_ALL_FACILITIES = `${PREFIX}/SET_ALL_FACILITIES`
export const SET_WHERE_USER_WORKS = `${PREFIX}/SET_WHERE_USER_WORKS`
