const PREFIX = 'GROUPS'

export const SET_GROUPS = `${PREFIX}/SET_GROUPS`
export const SET_LOADING = `${PREFIX}/SET_LOADING`
export const SET_POSITIONS = `${PREFIX}/SET_POSITIONS`
export const SET_CURRENT_GROUP = `${PREFIX}/SET_CURRENT_GROUP`
export const SET_MODAL = `${PREFIX}/SET_MODAL`
export const SET_SEARCH_VALUE = `${PREFIX}/SET_SEARCH_VALUE`
export const SET_DISCIPLINE_FILTER = `${PREFIX}/SET_DISCIPLINE_FILTER`
export const SET_SPORT_FILTER = `${PREFIX}/SET_SPORT_FILTER`
export const SET_AGES_FILTER = `${PREFIX}/SET_AGES_FILTER`
export const SET_CURRENT_PAGE = `${PREFIX}/SET_CURRENT_PAGE`
