const PREFIX = 'GROUPS_PERSONS'

export const SET_LOADING = `${PREFIX}/SET_LOADING`
export const SET_PERSONS = `${PREFIX}/SET_PERSONS`
export const SET_MODAL = `${PREFIX}/SET_MODAL`
export const SET_SEARCH_VALUE = `${PREFIX}/SET_SEARCH_VALUE`
export const SET_CURRENT_PAGE = `${PREFIX}/SET_CURRENT_PAGE`
export const SET_POSITION_FILTER = `${PREFIX}/SET_POSITION_FILTER`
export const SET_CURRENT_PERSON = `${PREFIX}/SET_CURRENT_PERSON`
